POST http://localhost:3000/api/operation/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InVzZXIxMjMiLCJwYXNzd29yZCI6IiQyYiQwNCRXeklLUmJrRkNMdXVuWjZmUzVqRTVlMG1wQTRPUDZIL1BMSG9tV2d4enBMQmwwSmpnaTMuTyIsImlhdCI6MTY2MDU2NTAxNn0.ji4iywVPZYn0PjdB8Ps_YAevaG7CNtbrc0b_ZIwTZKs

{
    "username": "user123"
}