POST http://localhost:3000/api/operation/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InVzZXIxMjMiLCJ0aW1lc3RhbXAiOjE2NjA2MDc3MzcsImlhdCI6MTY2MDYwNzczN30.0ePeBhrTiacJWuOZ6bbnHJFJiZZMt97vrvzVoXdE8sw

{
    "username": "user123"
}